export const Strings = {
  appName: 'مزرعتي',
  welcome: 'مرحباً',
  tabs: {
    home: 'الرئيسية',
    monitoring: 'المراقبة',
    flock: 'قطيعي',
    reports: 'التقارير',
    community: 'المجتمع',
    store: 'المتجر',
  },
  home: {
    greeting: 'مرحباً أحمد 👋',
    subtitle: 'مزرعة الأمل — يوم موفق!',
    quickStats: 'نظرة سريعة',
    temperature: 'درجة الحرارة',
    humidity: 'الرطوبة',
    birdCount: 'عدد الطيور',
    mortality: 'نسبة النفوق',
    alerts: 'التنبيهات',
    noAlerts: 'لا توجد تنبيهات اليوم',
    alertTemp: 'تحذير: درجة الحرارة مرتفعة!',
    todayFeed: 'العليقة اليوم',
    kg: 'كغ',
  },
  monitoring: {
    title: 'مراقبة البيئة',
    temperature: 'درجة الحرارة',
    humidity: 'الرطوبة',
    co2: 'ثاني أكسيد الكربون',
    ventilation: 'التهوية',
    light: 'الإضاءة',
    celsius: '°م',
    percent: '%',
    ppm: 'جزء/مليون',
    lux: 'لكس',
    live: 'مباشر',
    history: 'آخر 24 ساعة',
    optimal: 'مثالي',
    warning: 'تحذير',
    critical: 'حرج',
    chartLabel: 'درجة الحرارة',
  },
  flock: {
    title: 'إدارة القطيع',
    totalBirds: 'إجمالي الطيور',
    mortalityRate: 'نسبة النفوق',
    age: 'العمر',
    days: 'يوم',
    breed: 'السلالة',
    avgWeight: 'متوسط الوزن',
    kg: 'كغ',
    feedConsumption: 'استهلاك العليقة',
    waterConsumption: 'استهلاك الماء',
    feedToday: 'العليقة اليوم',
    waterToday: 'الماء اليوم',
    liter: 'لتر',
    health: 'الحالة الصحية',
    excellent: 'ممتاز',
    good: 'جيد',
    attention: 'يحتاج متابعة',
    batches: 'الدفعات',
    batch: 'الدفعة',
  },
  reports: {
    title: 'التقارير والإحصائيات',
    daily: 'يومي',
    weekly: 'أسبوعي',
    monthly: 'شهري',
    totalDeaths: 'إجمالي النفوق',
    survivalRate: 'نسبة البقاء',
    productionCost: 'تكلفة الإنتاج',
    revenue: 'الإيرادات',
    profit: 'الربح',
    feedCost: 'تكلفة العليقة',
    chart: {
      mortality: 'النفوق اليومي',
      feed: 'استهلاك العليقة',
      weight: 'نمو الوزن',
    },
  },
  store: {
    title: 'متجر الدواجن',
    categories: {
      all: 'الكل',
      feed: 'العلائق',
      medicine: 'الأدوية',
      equipment: 'المعدات',
      vaccine: 'اللقاحات',
    },
    addToCart: 'أضف للسلة',
    price: 'السعر',
    currency: 'دج',
    inStock: 'متوفر',
    outOfStock: 'غير متوفر',
    search: 'ابحث عن منتج...',
  },
  community: {
    title: 'مجتمع المربين',
    share: 'شارك تجربتك',
    like: 'إعجاب',
    comment: 'تعليق',
    reply: 'رد',
    followers: 'متابع',
    following: 'يتابع',
    experts: 'خبراء',
    tips: 'نصائح',
    questions: 'أسئلة',
    ago: {
      minutes: 'دقيقة',
      hours: 'ساعة',
      days: 'يوم',
    },
  },
};
